language: go

# use containers which run faster and have cache
sudo: false

go:
  - 1.10.x

go_import_path: github.com/zaquestion/truss

notifications:
  email: false

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux

env:
  global:
    secure: fhgA49Ydk/M7erDKMC4gECftUe3+MYRNA3ksvLVMMQ9K0Si+2cj7v3USaXKjs6GA4+r6s2vnwBPDAu8Utuj//qb4nIHrpFPymGqWkOjZ9mpiahJs4URMQRTRC0/Oh3bQJr4dMztaiD3qTbn+TY6KmpI46O0urUhJm9S6q5UpN/n9b7bvx4YtC0dmXkHfrT1w2E2JynJXSV2Ve+Zdvds4UAPcvg9op6fAsB6wrGACO56ueo6hLmKLbuxDIxJ4xWA1V/ZP0vJ3cP7/UAcnCo+S1waq2xt0+CfSddA/K6r40dt2xZ1JmqBln/TgAEf/yD8KdETAtlB9wk21ycDoVxSRfqA6fGIj3w8o0mgf+VnSeOo+FyXwx5t7L+1vCh+mXGOk6Hj9RhlCZrV9R0xwd086e/bKrRsLPU8bafrPkYmmhU3iMhtwxOqfpX1z+M3vuti5im8TlIcol0InK/INf+BwTC5axzB2xBmJIPhCWNlkLGmtVU36VzsDdyQhKBXGRh4ITSxOA2jaJnobxu/rBsSBjxQjm89AcK72iU5WKxSTIi5bajAeTOduGKK2pez6ZgpoWRClO+vz5EWY2lcEPAHPkhQ44U0I0LzQqGJbHH+OOq+e6hsKiYEANbDkFDxU0r3I0e4iPT7xGibhI5+6jG3VXUB8DTv6wQ8m1YFPjpUl8L4=
