language: go

# use containers which run faster and have cache
sudo: false

go:
  - 1.10.x

go_import_path: github.com/tuneinc/truss
before_install:
  # protobuf
  # download, unzip in $HOME, add to $PATH
  - wget https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
  - mv protoc-3.2.0-linux-x86_64.zip $HOME
  - unzip ~/protoc-3.2.0-linux-x86_64.zip -d $HOME
  - export PATH=$HOME/bin/:$PATH

  # Dependencies
  - go get -v github.com/golang/protobuf/protoc-gen-go
  - go get -v github.com/jteeuwen/go-bindata/...

install:
  # install our protoc plugin and truss
  - make dependencies
  - make

notifications:
  email: false

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux

env:
  global:
    secure: "ZjnLJERNOxHlIcjxK3nkRZq8C8hNMTVnqNKPGj6yhF45F3JAmEn2mzdBbCUqO2AOeBzCm2sPxIGOR9Tc4FJ6LrKn1k8AQ6eKYOlJL2mfjadCIavEP34j4tnqzfK8mG2QAWe5JInL5dL+Wcsk/9tD0/bLBplFlHuu34V5uIUu1vahDymlvk3xkkHNMj0sqUwa0vNgAhIu2dTbXz3TMpUGoIFFSE4APU9DuotrbTil3qVwwOCfAwCR3P/1yVn6l99foxZx7SYtWCm/dKIvFY75sSkvfGEXJwDkWjdS7LihbOnp1qA4EHGMGr/1CayPvogFIhWczKvT/mBlPfU3g04T2mk+tPYdzxlmbZ75jTHT9rW+Q6eA6Vb4i7waaE7keTO/0WFWi2rFo74WuF6Yu/PWwPE5VIJVJt7mU/5ppaXonWn+x/goy6iGOM51RcJtWioiR/wVyVk7TTrv+7CJ5hQ1/PvlCcxFUZvZdTFOzHwkE7jqnLFoKzdgMsXbWBQZVb740BaNwaMRXjQ99mV8k3o54c9BthSAMeHmP9ptaZHKlxVPyEIErB/gms0eDz+7xGv49WOycs3zgyG4+jRMtolo4qM1cSyu6sXqc5YXhZKjgU7z129ZvytXuyCTVQXiD9R0p6iJc0l/TxhlzDFtNi5F/khLNbDrjVE/RiPbbv2D2rs="
