language: go

# use containers which run faster and have cache
sudo: false

notifications:
  email: false

go:
  - 1.9.x
  - 1.10.x
  - master

stages:
  - test
  - name: deploy
    if: tag IS present

go_import_path: github.com/tuneinc/truss
before_install:
  # protobuf
  # download, unzip in $HOME, add to $PATH
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - mv protoc-3.5.1-linux-x86_64.zip $HOME
  - unzip ~/protoc-3.5.1-linux-x86_64.zip -d $HOME
  - export PATH=$HOME/bin/:$PATH

install:
  # install our protoc plugin and truss
  - make dependencies
  - make

jobs:
  include:
    - stage: test
      script: make test
    - stage: deploy
      go: 1.10.x
      script: curl -sL https://git.io/goreleaser | bash

matrix:
  allow_failures:
    - go: master
  fast_finish: true
